name: Test

outputs:
  ref: ${{ env.GITHUB_REF }}

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ''

      - name: Install dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn unit

      - name: Run e2e Tests on Chrome
        uses: cypress-io/github-action@v3
        with:
          project: .
          browser: chrome
          build: yarn build
          start: yarn preview
          wait-on: 'http://localhost:4173'

      - name: Run e2e Tests on Firefox
        uses: cypress-io/github-action@v3
        with:
          project: .
          browser: firefox
          build: yarn build
          start: yarn preview
          wait-on: 'http://localhost:4173'
